name: My FastAPI CI/CD workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: Run my FastAPI tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pytest

  build:
    name: Build and Push the Docker image
    needs: run-tests
    runs-on: ubuntu-20.04
    env:
      COMMIT_SHA: ${{ GITHUB_SHA }}
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: reachincubator/fastapi-example: ${{ env.COMMIT_SHA }}
