name: My FastAPI CI/CD workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: Run my FastAPI tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pytest

  build:
    name: Build and Push the Docker image
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set the Docker image tag
        run: echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: reachincubator/fastapi-example:${{ env.GIT_COMMIT }}
          build-args: |
            GIT_COMMIT=${{ env.GIT_COMMIT }}
    
    deploy:
      name: Deploy the Docker image at Kubernetes
      needs: build
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout the repository
          uses: actions/checkout@v2
        - name: Set the Docker image tag
          run: echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
        - name: Variable substitution
          uses: microsoft/variable-substitution@v1 
          with:
            files: 'kubernetes/deployment.yaml'
          env:
            GIT_COMMIT: ${{ env.GIT_COMMIT }}
        - name: Deploy app at Kubernetes cluster
          uses: colbyhill21/Rancher-Action@1.1
          with: 
            args: '"kubectl apply -f kubernetes/deployment.yaml"'
            token: ${{ secrets.RANCHER_TOKEN }}
            context: ${{ secrets.RANCHER_CONTEXT }}
            url: ${{ secrets.RANCHER_URL }}