name: My FastAPI CI/CD workflow
on:
  pull_request:
    branches:
      - main
      - '!argocd*'
jobs:
  build:
    name: Build and Push the Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set the Docker image tag
        run: echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: reachincubator/fastapi-example:${{ env.GIT_COMMIT }}
          build-args: |
            GIT_COMMIT=${{ env.GIT_COMMIT }}
