name: My FastAPI CI workflow
on: [push]
jobs:
  run-tests:
    name: Run my FastAPI tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pytest
